#!/usr/bin/env python3

import rospy
import math
import time
from krssg_ssl_msgs.msg import SSL_DetectionFrame
from grsim_ros_bridge_msgs.msg import *

robots_pose = [[],[],[],[],[]]
robots_coordinates = [[],[],[],[],[]]
ball = []
j =0
def callback(data):
    global ball, robots, j

    if len(data.balls) > 0: 
        ball = [data.balls[0].x, data.balls[0].y]
    
    if len(data.robots_blue) > 0:
        i = 0
        while i < len(data.robots_blue):
            robot_idx = data.robots_blue[i].robot_id
            robots_pose[robot_idx] = [data.robots_blue[i].x, data.robots_blue[i].y, data.robots_blue[i].orientation]
            robots_coordinates[robot_idx] = [data.robots_blue[i].x, data.robots_blue[i].y]
            i = i+1

if __name__ == '__main__':

    while not rospy.is_shutdown():

        rospy.init_node('listener', anonymous=True)
        rospy.Subscriber("/vision", SSL_DetectionFrame, callback)
        